# Generated by Django 6.0.1 on 2026-01-27 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18, message='Age must be at least 18')]),
        ),
    ]
